blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('',views.blogs,name="blogs"),
    path('show-blog/<uuid:pk>/',views.show_blog,name="show-blog"),
    path('featured/', views.featured, name="featured"),  
    path('add-comment/',views.add_comment,name="add-comment"),
    path('blog-form/', views.create_blog, name="blog-form"),  # Modified path for blog form
    path('blog-form/<int:blog_id>/', views.create_blog, name='edit-blog'), 
    path('search/', views.search, name="search"),  # Modified path for blog form
    path('delete-blog/<uuid:blog_id>', views.delete_blog, name="delete-blog"),  # Modified path for blog form
    path('delete-confirmation/<uuid:blog_id>', views.delete_confirmation, name="delete-confirmation"),  # Modified path for blog form
    path('categories/<str:category>/', views.category, name="category"),  # Modified path for blog form
    path('<str:username>/', views.user_blogs, name="user-blogs"),  
    
]

chikaness/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from users import views as user_views
from django.contrib.auth import views as authentication_views

from django.views.static import serve

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^pictures/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('',include('users.urls')),
    path('blogs/',include('blogs.urls')),
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',user_views.logout_view,name="logout"),
    path('<str:username>/',user_views.profile,name='profile')
]

urlpatterns += [
    
]  +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from users.models import User
import uuid
from datetime import datetime

class Blog(models.Model):
    CATEGORIES = [
        ('education', 'Education'),
        ('music', 'Music'),
        ('personal', 'Personal'),
        ('promotions', 'Promotions'),
        ('travels', 'Travels'),
        ('others', 'Others')
    ]
    
    DEFAULT_CATEGORY = 'others' 
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)    
    featured = models.BooleanField(default=False)
    pen_name = models.CharField(max_length=100, null=True, blank=True)
    teaser = models.TextField(max_length=255, null=True, blank=True)
    category = models.CharField(max_length=50, choices=CATEGORIES, default=DEFAULT_CATEGORY)
    content = models.TextField()
    content2 = models.TextField(null=True, blank=True)
    content3 = models.TextField(null=True, blank=True)
    content4 = models.TextField(null=True, blank=True)
    content5 = models.TextField(null=True, blank=True)
    content6 = models.TextField(null=True, blank=True)
    content7 = models.TextField(null=True, blank=True)
    content8 = models.TextField(null=True, blank=True)
    content9 = models.TextField(null=True, blank=True)
    content10 = models.TextField(null=True, blank=True)
    image = models.ImageField(default='blog-default.jpeg', upload_to='blog_pics')
    image_end = models.ImageField(null=True, blank=True, upload_to='blog_pics')    
    image2 = models.ImageField(null=True, blank=True, upload_to='blog_pics')
    image3 = models.ImageField(null=True, blank=True, upload_to='blog_pics')
    image4 = models.ImageField(null=True, blank=True, upload_to='blog_pics')
    image5 = models.ImageField(null=True, blank=True, upload_to='blog_pics')
    image6 = models.ImageField(null=True, blank=True, upload_to='blog_pics')
    image7 = models.ImageField(null=True, blank=True, upload_to='blog_pics')
    image8 = models.ImageField(null=True, blank=True, upload_to='blog_pics')
    image9 = models.ImageField(null=True, blank=True, upload_to='blog_pics')
    image_end_caption = models.CharField(max_length=255, null=True, blank=True)
    image2_caption = models.CharField(max_length=255, blank=True, default="Photo has no caption")
    image3_caption = models.CharField(max_length=255, blank=True, default="Photo has no caption")
    image4_caption = models.CharField(max_length=255, blank=True, default="Photo has no caption")
    image5_caption = models.CharField(max_length=255, blank=True, default="Photo has no caption")
    image6_caption = models.CharField(max_length=255, blank=True, default="Photo has no caption")
    image7_caption = models.CharField(max_length=255, blank=True, default="Photo has no caption")
    image8_caption = models.CharField(max_length=255, blank=True, default="Photo has no caption")
    image9_caption = models.CharField(max_length=255, blank=True, default="Photo has no caption")
    
    created_at = models.DateTimeField(default=datetime.now)
    
    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return f"{self.author} -- {self.title}"
    
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = created_at = models.DateTimeField(default=datetime.now)
    
    def __str__(self):
        return f"Comment by {self.user.username} on blog {self.blog.title}"
    

blogs/forms.py
from django import forms
from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'pen_name', 'teaser', 'content', 'content2', 'content3', 'content4', 'content5', 'content6', 'content7', 'content8', 'content9', 'content10', 'category', 'image', 'image_end', 'image2', 'image3', 'image4', 'image5', 'image6', 'image7', 'image8', 'image9', 'image_end_caption', 'image2_caption', 'image3_caption', 'image4_caption', 'image5_caption', 'image6_caption', 'image7_caption', 'image8_caption', 'image9_caption']

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import Blog, User, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.contrib import messages
from .forms import BlogForm
from django.contrib.auth.decorators import login_required

def blogs(request):
    all_blogs = Blog.objects.all()
    
    # Number of blogs to display per page
    per_page = 18  # You can adjust this as needed
    
    # Paginate blogs
    paginator = Paginator(all_blogs, per_page)
    
    # Get current page number from request, default to 1
    page_number = request.GET.get('page', 1)

    try:
        # Get blogs for the requested page
        blogs_page = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page
        blogs_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver last page of results
        blogs_page = paginator.page(paginator.num_pages)
    
    return render(request, 'blogs/index.html', {'blogs':blogs_page})

def show_blog(request, pk):
    # Retrieve the blog post using the primary key (pk)
    blog = get_object_or_404(Blog, id=pk)
    
    comments = Comment.objects.filter(blog=blog)
    
    # Pass the blog object to the template for rendering
    return render(request, 'blogs/blog.html', {'blog': blog, 'comments':comments})

@login_required
def create_blog(request, blog_id=None):
    categories = Blog.CATEGORIES
    if blog_id:
        blog = get_object_or_404(Blog, pk=blog_id)
    else:
        blog = None
    
    if request.method == 'POST':
        # Create a form instance and populate it with data from the request
        form = BlogForm(request.POST, request.FILES)
        
        # Retrieve data from the request
        title = request.POST.get('title')
        pen_name = request.POST.get('pen_name')
        teaser = request.POST.get('teaser')
        content = request.POST.get('content')
        content2 = request.POST.get('content2')
        content3 = request.POST.get('content3')
        content4 = request.POST.get('content4')
        content5 = request.POST.get('content5')
        content6 = request.POST.get('content6')
        content7 = request.POST.get('content7')
        content8 = request.POST.get('content8')
        content9 = request.POST.get('content9')
        content10 = request.POST.get('content10')
        
        # Image fields
        image = request.FILES.get('image')
        image_end = request.FILES.get('image_end')
        image2 = request.FILES.get('image2')
        image3 = request.FILES.get('image3')
        image4 = request.FILES.get('image4')
        image5 = request.FILES.get('image5')
        image6 = request.FILES.get('image6')
        image7 = request.FILES.get('image7')
        image8 = request.FILES.get('image8')
        image9 = request.FILES.get('image9')
        
        # Image caption fields
        image_end_caption = request.POST.get('image_end_caption')
        image2_caption = request.POST.get('image2_caption')
        image3_caption = request.POST.get('image3_caption')
        image4_caption = request.POST.get('image4_caption')
        image5_caption = request.POST.get('image5_caption')
        image6_caption = request.POST.get('image6_caption')
        image7_caption = request.POST.get('image7_caption')
        image8_caption = request.POST.get('image8_caption')
        image9_caption = request.POST.get('image9_caption')
        
        # Retrieve the category from the request
        category = request.POST.get('category')
        
        # Assuming the current user is the author
        author = request.user

        # Create a new Blog object
        blog = Blog(
            title=title,
            pen_name=pen_name,
            teaser=teaser,
            content=content,
            content2=content2,
            content3=content3,
            content4=content4,
            content5=content5,
            content6=content6,
            content7=content7,
            content8=content8,
            content9=content9,
            content10=content10,
            image=image,
            image_end=image_end,
            image2=image2,
            image3=image3,
            image4=image4,
            image5=image5,
            image6=image6,
            image7=image7,
            image8=image8,
            image9=image9,
            image_end_caption=image_end_caption,
            image2_caption=image2_caption,
            image3_caption=image3_caption,
            image4_caption=image4_caption,
            image5_caption=image5_caption,
            image6_caption=image6_caption,
            image7_caption=image7_caption,
            image8_caption=image8_caption,
            image9_caption=image9_caption,
            category=category, 
            author=author,
            # Add more fields as needed
        )
        
        if form.is_valid():  # Check if the form data is valid
            # If the form is valid, save the blog object
            blog = form.save(commit=False)
            blog.author = request.user  # Assuming the current user is the author
            blog.save()
            
            messages.success(request, 'Blog published! Good job!')
            return redirect('blogs:blogs')
        
        else:
            messages.error(request, 'There was an issue processing the form. Check your input and try again.')
    else:
        # If the request method is not POST, 
        form = BlogForm()        
    
    return render(request, 'blogs/blog_form.html', {'categories': Blog.CATEGORIES})


def category(request, category):
    # Get blogs belonging to the specified category
    blogs = Blog.objects.filter(category__iexact=category)

    # Number of blogs to display per page
    per_page = 18  # You can adjust this as needed

    # Paginate blogs
    paginator = Paginator(blogs, per_page)

    # Get current page number from request, default to 1
    page_number = request.GET.get('page', 1)

    try:
        # Get blogs for the requested page
        blogs_page = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page
        blogs_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver last page of results
        blogs_page = paginator.page(paginator.num_pages)

    return render(request, 'blogs/categories.html', {'category': category, 'blogs': blogs_page})

def featured(request):
    # Get blogs belonging to the specified category
    featured_blogs = Blog.objects.filter(featured=True)

    # Number of blogs to display per page
    per_page = 18  # You can adjust this as needed

    # Paginate blogs
    paginator = Paginator(featured_blogs, per_page)

    # Get current page number from request, default to 1
    page_number = request.GET.get('page', 1)

    try:
        # Get blogs for the requested page
        blogs_page = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page
        blogs_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver last page of results
        blogs_page = paginator.page(paginator.num_pages)

    return render(request, 'blogs/featured.html', {'blogs': blogs_page})

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def search(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        filtered_blogs = Blog.objects.filter(title__icontains=title)[:24]
        
        return render(request, 'blogs/search.html', {'blogs': filtered_blogs})


def delete_blog(request, blog_id):
    # Retrieve the blog object from the database
    blog = get_object_or_404(Blog, pk=blog_id)

    # Check if the request method is POST (the form is submitted)
    if request.method == 'POST':
        if blog.author == request.user:
            blog.delete()
            messages.success(request, 'Blog deleted.')
        
            return redirect('blogs:blogs')

    # If the request method is not POST, render a confirmation template
    return render(request, 'blogs/index.html', {'blog': blog})

def delete_confirmation(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    return render(request, 'blogs/delete_confirmation.html', {'blog':blog})

def user_blogs(request, username):
    # Retrieve the user object based on the username
    user = User.objects.get(username=username)
    
    # Retrieve the blogs authored by the user
    user_blogs = Blog.objects.filter(author=user)
    
    # Number of blogs to display per page
    per_page = 18  # You can adjust this as needed

    # Paginate blogs
    paginator = Paginator(user_blogs, per_page)

    # Get current page number from request, default to 1
    page_number = request.GET.get('page', 1)

    try:
        # Get blogs for the requested page
        blogs_page = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page
        blogs_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver last page of results
        blogs_page = paginator.page(paginator.num_pages)
    
    # Pass the user blogs to the template context
    context = {
        'user': user,
        'blogs': blogs_page,
    }
    
    return render(request, 'blogs/user_blogs.html', context)

@login_required
def add_comment(request):
    if request.method == 'POST':
        content = request.POST.get('content', '').strip()
        blog_id = request.POST.get('blog_id') 
        
        if content and blog_id:
            user = request.user
            blog = Blog.objects.get(id=blog_id)
            
            # Create the comment object

blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}
{% load static %}
{% block content %}

<head>
    <<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Page Title</title>
    
    <!-- Open Graph meta tags for Facebook -->
    <meta property="og:title" content="{{ blog.title }}">
    <meta property="og:description" content="Description of your page">
    <meta property="og:image" content="URL to your thumbnail image">
    <meta property="og:url" content="{% url 'blogs:show-blog' pk=blog.id %}">
    <meta property="og:type" content="website">
    
    <!-- Facebook SDK script -->
    <div id="fb-root"></div> 
    <script async defer crossorigin="anonymous" 
            src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v9.0" 
            nonce="8E6OZDVx"></script> 

            <style>
                .fb-share-button {
                    margin-top: 30px;
                    display: inline-block;
                    background-color: #43609C;
                    color: white;
                    font-family: Arial, sans-serif;
                    font-size: 12px;
                    padding: 10px 12px;
                    border-radius: 5px;
                    text-decoration: none;
                }
            </style>
</head>
<div class="mt-3 pt-2">
{% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} bg-warning">
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
</div>
<div class="container-lg mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-5 text-center">
            <h1>
                <div class="display-5 text-muted">{{blog.title}}</div>
            </h1>
            {% if blog.pen_name is not None %}
            
                <i><a style="text-decoration:none" class="text-warning" href="{% url 'profile' blog.author.username %}">{{blog.pen_name}}</a></i>
            {% else %}
                <i><a style="text-decoration:none" class="text-warning" href="{% url 'profile' blog.author.username %}">{{blog.author}}</a></i>
            {% endif %}
        <hr>
        </div>
        
            <div class="col-md-8 text-center">
                {% if blog.image %}
                <img style="width:100%;height:auto" src="{{blog.image.url}}">
                {% else %}
                <img style="width:100%;height:auto" src="{% static 'blogs/images/blog-default.jpeg' %}">
                {% endif %}
            </div>
        
        <div class="col-sm-8 text-start">
            <p class="lead my-4 text-muted">{{blog.content|linebreaks}}</p>
            
            {% if blog.image2 %}
            <hr>
            <div class="row align-items-center">
                <div class="col-8">
                    <img style="width:100%;height:auto;object-fit:cover" src="{{blog.image2.url}}">
                </div>    
                <div class="col-4">
                    <p class="text-muted" style="font-size:10px;"><i>{{blog.image2_caption}}</i></p>
                </div>
                            
            </div>
            {% endif %}
            {% if blog.content2 %}
            <p class="lead my-4 text-muted">{{blog.content2|linebreaks}}</p>
            {% endif %}


            {% if blog.image3 %}
            <hr>
            <div class="row align-items-center">
                <div class="col-4">
                    <p class="text-muted" style="font-size:10px;"><i>{{blog.image3_caption}}</i></p>
                </div>
                <div class="col-8">
                    <img style="width:100%;height:auto;object-fit:cover" src="{{blog.image3.url}}">
                </div>                
            </div>
            {% endif %}
            {% if blog.content3 %}
            <p class="lead my-4 text-muted">{{blog.content3|linebreaks}}</p>
            {% endif %}

            {% if blog.image4 %}
            <hr>
            <div class="row align-items-center">
                <div class="col-8">
                    <img style="width:100%;height:auto;object-fit:cover" src="{{blog.image4.url}}">
                </div>     
                <div class="col-4">
                    <p class="text-muted" style="font-size:10px;"><i>{{blog.image4_caption}}</i></p>
                </div>                           
            </div>
            {% endif %}
            {% if blog.content4 %}
            <p class="lead my-4 text-muted">{{blog.content4|linebreaks}}</p>
            {% endif %}

            {% if blog.image5 %}
            <hr>
            <div class="row align-items-center">
                <div class="col-4">
                    <p class="text-muted" style="font-size:10px;"><i>{{blog.image5_caption}}</i></p>
                </div>
                <div class="col-8">
                    <img style="width:100%;height:auto;object-fit:cover" src="{{blog.image5.url}}">
                </div>                
            </div>
            {% endif %}
            {% if blog.content5 %}
            <p class="lead my-4 text-muted">{{blog.content5|linebreaks}}</p>
            {% endif %}

            {% if blog.image6 %}
            <hr>
            <div class="row align-items-center">
                <div class="col-8">
                    <img style="width:100%;height:auto;object-fit:cover" src="{{blog.image6.url}}">
                </div>        
                <div class="col-4">
                    <p class="text-muted" style="font-size:10px;"><i>{{blog.image6_caption}}</i></p>
                </div>
                        
            </div>
            {% endif %}
            {% if blog.content6 %}
            <p class="lead my-4 text-muted">{{blog.content6|linebreaks}}</p>
            {% endif %}

            {% if blog.image7 %}
            <hr>
            <div class="row align-items-center">
                <div class="col-4">
                    <p class="text-muted" style="font-size:10px;"><i>{{blog.image7_caption}}</i></p>
                </div>
                <div class="col-8">
                    <img style="width:100%;height:320px;object-fit:cover" src="{{blog.image7.url}}">
                </div>                
            </div>
            {% endif %}
            {% if blog.content7 %}
            <p class="lead my-4 text-muted">{{blog.content7|linebreaks}}</p>
            {% endif %}

            {% if blog.image8 %}
            <hr>
            <div class="row align-items-center">
                <div class="col-8">
                    <img style="width:100%;height:320px;object-fit:cover" src="{{blog.image8.url}}">
                </div>     
                <div class="col-4">
                    <p class="text-muted" style="font-size:10px;"><i>{{blog.image8_caption}}</i></p>
                </div>                           
            </div>
            {% endif %}
            {% if blog.content8 %}
            <p class="lead my-4 text-muted">{{blog.content8|linebreaks}}</p>
            {% endif %}

            {% if blog.image9 %}
            <hr>
            <div class="row align-items-center">
                <div class="col-4">
                    <p class="text-muted" style="font-size:10px;"><i>{{blog.image9_caption}}</i></p>
                </div>
                <div class="col-8">
                    <img style="width:100%;height:320px;object-fit:cover" src="{{blog.image9.url}}">
                </div>                
            </div>
            {% endif %}
            {% if blog.content9 %}
            <p class="lead my-4 text-muted">{{blog.content9|linebreaks}}</p>
            {% endif %}

            {% if blog.image_end %}
            <hr>
            <div class="row align-items-center">
                <div class="col-8">
                <img style="width:100%;height:320px;object-fit:cover" src="{{blog.image_end.url}}">
                </div>
                <div class="col-4">
                <p class="text-muted" style="font-size:10px;"><i>{{blog.image_end_caption}}</i></p>
                </div>
            </div>
            {% endif %}
            <div class="fb-share-button" 
                data-href="{% url 'blogs:show-blog' pk=blog.id %}" 
                data-layout="button" data-size="small" data-mobile-iframe="false">
                <a class="fb-xfbml-parse-ignore" target="_blank" href="{% url 'blogs:show-blog' pk=blog.id %}">Share
                </a>
            </div>
        </div>        
        </div>    
    </div>
    <div class="text-center">
        {% if user.is_authenticated %}
            {% if blog.author == user %}
            <a href="{% url 'blogs:delete-confirmation' blog_id=blog.id %}" class="btn btn-outline-warning">Delete Blog</a>
            {% comment %} <a href="{% url 'blogs:edit-blog' blog_id=blog.id %}" class="btn btn-outline-warning">Edit Blog</a> {% endcomment %}
            {% endif %}
        {% endif %}
        
    </div>

<!-- comments -->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            

        {% if user.is_authenticated %}
            <form action="{% url 'blogs:add-comment' %}" method="POST" id="{{blog.id}}">
                {% csrf_token %}
                <input type="hidden" name="blog_id" value="{{ blog.id }}"> <!-- Hidden input field for post ID -->
                <div class="form-group">
                    <label for="id_content">Leave a comment:</label>
                    <textarea class="form-control" id="id_content" name="content" rows="3" required></textarea>
                </div><br>
                <button type="submit" class="btn btn-warning">Submit</button>
            </form>
            {% endif %}
        </div>
    </div>
</div>
<div class="container bg-light text-center mt-5 mb-4 pb-4">
    {% if comments %}    
    <div class="display-6 text-muted mb-5">Comments on this Blog:</div>
    {% for comment in comments reversed %}
    <div class="row justify-content-center">
        <div class="col-md-6 border border-top-0">
            <p>
                <a href="{% url 'profile' username=comment.user %}" style="text-decoration: none;">         
                    <span class="text-warning"><b>{{ comment.user }}</b></span>
                    <span style="font-size:10px; color:gray;">
                        ({{ comment.created_at|date:"M-d-Y" }}):
                    </span>
                </a>  
                    {{comment.content|linebreaks}}
            </p>
        </div>
    </div>
    {% endfor %} 
    {% else %}
    <div class="display-6 text-muted mb-5">No comment yet.</div>
    {% endif %}
    {% if not user.is_authenticated %}
    <p class="text-muted"><i>Log in to write a comment.</i></p>
    {% endif %}
</div> 
</div>    
{% endblock %}

blogs/templates/blogs/categories.html
{% extends 'blogs/base.html' %}

{% block content %}

<div class="pt-5 bg-dark">    
    <div class="container bg-dark pt-4">
        <h1 class="text-light">{{ category }}</h1>
        <hr style="color:white;">
        <div class="row">
            {% if user.is_authenticated %}
            <div class="">
                <h3 class="text-warning">Hey, wanna drop a blog post today?</h3><span>
                <a href="{% url 'blogs:blog-form' %}" class="btn btn-outline-warning">Yes, I'm feeling creative!</a>
                </span>
            </div>
            {% endif %}
            <hr>
            {% for blog in blogs %}
            {% if blog.featured %}
            <div class="col-md-6 col-lg-4 py-2 bg-light border border-dark border-5">
                <img class="border border-warning border-1" style="width:100%; height:300px; object-fit:cover;" src="{{ blog.image.url }}">
                <h2>{{ blog.title }} <span style="font-size:10px;">FEATURED <i class="bi bi-check-circle-fill text-warning"></i></span></h2>
                <i><a style="text-decoration:none" class="text-warning" href="{% url 'profile' blog.author.username %}">{{blog.author}}</a></i>
                <p class="text-muted">{{ blog.teaser }}</p>
                <a href="{% url 'blogs:show-blog' pk=blog.pk %}" class="btn btn-warning">Read Blog</a>
            </div>
            {% else %}
            <div class="col-md-6 col-lg-4 py-2 bg-light border border-dark border-5">            
                <img class="border border-warning border-1" style="width:100%; height:300px; object-fit:cover;" src="{{ blog.image.url }}">
                <h2>{{ blog.title }}</h2>
                <i><a style="text-decoration:none" class="text-warning" href="{% url 'profile' blog.author.username %}">{{blog.author}}</a></i>
                <p class="text-muted">{{ blog.teaser }}</p>
                <a href="{% url 'blogs:show-blog' pk=blog.id %}" class="btn btn-warning">Read Blog</a>
            </div>
        {% endif %}
            {% endfor %}
        </div>

        <div class="pagination">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item {% if not blogs.has_previous %}disabled{% endif %}">
                        <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% for page_num in blogs.paginator.page_range %}
                    <li class="page-item {% if page_num == blogs.number %}active{% endif %}">
                        <a class="page-link bg-dark" style="
                        border-radius:10px;" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                    {% endfor %}
                    {% if blogs.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ blogs.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <span class="page-link" aria-hidden="true">&raquo;</span>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>


    </div>
</div>

{%endblock%}

blogs/templates/blogs/delete_confirmation.html
{% extends 'blogs/base.html' %}
{% block content %}

<div class="container pt-2">
    <div class="pt-5">
        <h2>Are you sure you want to delete this blog?</h2>
        <div class="col-md-6 col-lg-4 py-2 bg-light border border-light border-2 px-2"
            style="border-radius:20px;">
            <img class="border border-warning border-1" style="width:100%; height:300px; object-fit:cover;" src="{{ blog.image.url }}">
            <h2 class="text-center">{{ blog.title }}</h2>
        </div>
        <br>
        <form action="{% url 'blogs:delete-blog' blog_id=blog.id %}" method='POST'>
            {% csrf_token %}
            <button class="btn btn-danger">Delete</button>
        </form>
        
        <br>
        <h4 class="text-muted"><i>This action cannot be undone.</i><h4>
            <a href="{% url 'blogs:show-blog' pk=blog.id %}" class="btn btn-outline-danger">Back to Blog</a>
    <div>
</div>

{% endblock %}