blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('',views.blogs,name="blogs"),
    path('show-blog/<uuid:pk>/',views.show_blog,name="show-blog"),
    path('featured/', views.featured, name="featured"),  
    path('add-comment/',views.add_comment,name="add-comment"),
    path('blog-form/', views.create_blog, name="blog-form"),  # Modified path for blog form
    path('blog-form/<int:blog_id>/', views.create_blog, name='edit-blog'), 
    path('search/', views.search, name="search"),  # Modified path for blog form
    path('delete-blog/<uuid:blog_id>', views.delete_blog, name="delete-blog"),  # Modified path for blog form
    path('delete-confirmation/<uuid:blog_id>', views.delete_confirmation, name="delete-confirmation"),  # Modified path for blog form
    path('categories/<str:category>/', views.category, name="category"),  # Modified path for blog form
    path('<str:username>/', views.user_blogs, name="user-blogs"),  
    
]

chikaness/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from users import views as user_views
from django.contrib.auth import views as authentication_views

from django.views.static import serve

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^pictures/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('',include('users.urls')),
    path('blogs/',include('blogs.urls')),
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',user_views.logout_view,name="logout"),
    path('<str:username>/',user_views.profile,name='profile')
]

urlpatterns += [
    
]  +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from .views import PostDeleteView, ProfilePostDeleteView

app_name = 'users'

urlpatterns = [
    path('',views.index,name='index'),
    path('comments/',views.comments,name='comments'),
    path('create_profile/', views.create_profile,name='create-profile'),
    path('follow', views.follow,name='follow'),
    path('<str:username>/followers', views.user_followers,name='user-followers'),
    path('<str:username>/following', views.user_following,name='user-following'),
    path('search/', views.search,name='search'),
    path('bulletin-board', views.post_to_bulletin_board, name="bulletin-board"),
    path('like-post', views.like_post, name="like-post"),
    path('likers/<uuid:pk>/', views.likers, name="likers"),
    path('add-comment', views.add_comment, name="add-comment"),
    path('delete-post/<uuid:pk>/', PostDeleteView.as_view(), name="delete-post"),
    path('profile-delete-post/<uuid:pk>/', ProfilePostDeleteView.as_view(), name="profile-delete-post"),
    path('profile-bulletin-board/<str:username>/', views.profile_bulletin_board, name="profile-bulletin-board"),
    path('bulletin-board-all/', views.show_bulletin_board, name='show-bulletin-board'),
    path('<str:username>/announcements/', views.user_announcements, name='user-announcements'),
]

users/models.py
from django.contrib.auth.models import User
from django.db import models
import uuid
from datetime import datetime

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    motto = models.TextField(max_length=300, default="Best friends don’t let you do stupid things alone.")
    about_yourself = models.TextField(max_length=2000, default="😀")
    profile_pic = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    q1 = models.TextField(max_length=1000, default="No answer yet.")
    q2 = models.TextField(max_length=1000, default="No answer yet.")
    q3 = models.TextField(max_length=1000, default="No answer yet.")
    q4 = models.TextField(max_length=1000, default="No answer yet.")
    verified = models.BooleanField(default=False)

    # create imagefield here
    
    def __str__(self):
        return self.user.username


class BulletinBoard(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(default='read-me.jpg', upload_to='announcement_pics')
    liked = models.ManyToManyField(User, default=None, blank=True, related_name='liked')
    created_at = models.DateTimeField(default=datetime.now)
    no_of_likes = models.IntegerField(default=0)
    no_of_comments = models.IntegerField(default=0)
    highlight = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.user} -- {self.content}"
    
class ProfileBulletinBoard(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4) 
    user = models.CharField(max_length=100)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, default=None)
    content = models.TextField()
    created_at = models.DateTimeField(default=datetime.now)
    
    def __str__(self):
        return f"Post by {self.user} - on {self.profile}'s profile"
    
class LikePost(models.Model):
    post = models.ForeignKey(BulletinBoard, on_delete=models.CASCADE, related_name='likes', default=None)
    username = models.CharField(max_length=500)
    
    def __str__(self):
        return f"{self.username} liked {self.post_id}"
    
class FollowersCount(models.Model):
    follower = models.CharField(max_length=100)
    user = models.CharField(max_length=100)
    
    def __str__(self):
        return f'{self.follower} started following {self.user}'
    

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('BulletinBoard', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(default=datetime.now)
    
    class Meta:
        ordering = ['-created_at']  # Order by 'created_at' field in descending order
    
    def __str__(self):
        return f"Comment by {self.user.username} on post {self.post.id}"
    

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['motto','about_yourself','profile_pic','q1','q2','q3','q4']

users/views.py
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DeleteView
from django.http import Http404, HttpResponse, JsonResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.contrib.auth.models import User, auth
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import auth
from django.http import HttpResponseServerError
from .models import Profile, BulletinBoard, ProfileBulletinBoard, LikePost, FollowersCount, Comment
from blogs.models import Blog
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from itertools import chain

def index(request):
    user_profile = None
    if request.user.is_authenticated:
        try:
            user_object = User.objects.get(username=request.user.username)
            user_profile = Profile.objects.get(user=user_object)
        except User.DoesNotExist or Profile.DoesNotExist:
            pass
    
    # Retrieve all posts without pagination
    all_posts = BulletinBoard.objects.all().order_by('-created_at') 
    
    user_following_list = []
    feed = []
    
    user_following = FollowersCount.objects.filter(follower=request.user.username)
        
    for users in user_following:
        user_following_list.append(users.user)
        
    for usernames in user_following_list:
        feed_lists = BulletinBoard.objects.filter(user=usernames).order_by('-created_at')
        feed.append(feed_lists)
        
    # Include highlighted posts
    highlighted_posts = BulletinBoard.objects.filter(highlight=True)
    
    feed_list = list(chain(*feed)) + list(highlighted_posts)
    
    # Slice the first 20 posts
    first_20_posts = feed_list[:18]
    
    
    return render(request, 'users/index.html', {'user_profile': user_profile, 'posts': first_20_posts})

@login_required
def post_to_bulletin_board(request):
    if request.method == 'POST':
        user = request.user.username
        content = request.POST.get('content', '').strip()  # Using get() to handle the case where 'content' is missing
        
        # Get the uploaded image from the request.FILES dictionary
        image = request.FILES.get('image')
        
        if content == '' or not image:
            messages.error(request, 'Announcement empty or no image attached. Cannot be posted.', extra_tags='custom-error')
            return redirect('/')
        
        try:
            new_post = BulletinBoard.objects.create(user=user, content=content)
            if image:
                new_post.image = image
            new_post.save()
            messages.success(request, f'Posted!')
            # No need to call new_post.save() explicitly, create() already saves the object
            return redirect('bulletin-board-all/')
        except Exception as e:
            # Log the error or print it for debugging
            print(f"An error occurred while creating the bulletin board post: {e}")
            # You can return an error response if needed
            return HttpResponseServerError("An error occurred while creating the bulletin board post.")
    else:
        return redirect('/')

@login_required
def like_post(request):
    if request.method == 'POST':
        username = request.user
        post_id = request.POST.get('post_id')
        
        # Ensure that the post_id is valid and exists
        if post_id:
            # Retrieve the BulletinBoard object based on the post_id
            post = get_object_or_404(BulletinBoard, id=post_id)
            
            # Check if the user has already liked the post
            if username in post.liked.all():
                post.liked.remove(username)
                post.no_of_likes -= 1
                LikePost.objects.filter(post_id=post_id, username=username).delete()
            else:
                post.liked.add(username)
                post.no_of_likes += 1
                LikePost.objects.create(post_id=post_id, username=username)
            
            post.save()  # Save the changes to the post object
            return redirect('users:show-bulletin-board')  # Redirect to the homepage or previous page after liking/unliking
        else:
            # Handle the case where post_id is not provided
            return HttpResponse("Invalid post ID", status=400)
    else:
        # Return a response indicating that the method is not allowed
        return HttpResponse("Method Not Allowed", status=405)

def likers(request, pk):
    # Get the BulletinBoard object with the given primary key
    post = get_object_or_404(BulletinBoard, id=pk)
    
    # Check if the post has been liked by any users
    if hasattr(post, 'liked'):
        likers = post.liked.all()
    else:
        likers = []
        
    # Fetch comments related to the specific post
    comments = Comment.objects.filter(post=post)

    return render(request, 'users/likers.html', {'likers': likers, 'post':post, 'comments':comments})

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = BulletinBoard
    success_url = reverse_lazy('users:show-bulletin-board')

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def delete(self, request, *args, **kwargs):
        # Get the object to be deleted
        self.object = self.get_object()
        
        # Check if the current user is the owner of the post
        if self.object.user == self.request.user:
            # Delete the post
            self.object.delete()

            # Add success message
            messages.success(self.request, f'Announcement successfully deleted.')
            
        else:
            # Add error message
            messages.error(self.request,f'You do not have permission to delete this announcement.')
            
            
        return HttpResponseRedirect(self.get_success_url())

class ProfilePostDeleteView(LoginRequiredMixin, DeleteView):
    model = ProfileBulletinBoard
    # success_url = reverse_lazy('profile')

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def delete(self, request, *args, **kwargs):
        # Get the object to be deleted
        self.object = self.get_object()
        
        # Check if the current user is the owner of the post
        if self.object.user == self.request.user:
            # Delete the post
            self.object.delete()

            # Add success message
            messages.success(self.request, f'Announcement deleted.')
            
        else:
            # Add error message
            messages.error(self.request,f'You do not have permission to delete this announcement.')
            
            
        return redirect('profile',username=self.object.profile.user.username)
    
    def get_success_url(self):
        # Redirect to the profile page of the user whose announcement was deleted
        return reverse_lazy('profile', kwargs={'username': self.object.profile.user.username})
    
def user_announcements(request, username):
    profile = get_object_or_404(Profile, user__username=username)
    announcement_list = BulletinBoard.objects.filter(user=username).order_by('-created_at')
    
    paginator = Paginator(announcement_list, 18)
    page_number = request.GET.get('page', 1)  

    try:
        announcements = paginator.page(page_number)
    except PageNotAnInteger:
        announcements = paginator.page(1)
    except EmptyPage:
        announcements = paginator.page(paginator.num_pages)
    
    return render(request, 'users/user-announcements.html', {'announcements': announcements, 'username': username, 'profile':profile})
    
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')  # Retrieve username
            password = form.cleaned_data.get('password1')  # Retrieve password
            form.save()
            
            user = User.objects.get(username=username)
            user_login = auth.authenticate(username=username, password=password)
            auth.login(request, user_login)
            
            Profile.objects.create(user=user)  # Create a Profile object for the user
            
            messages.success(request,f'Welcome <span style="font-weight:bold;">{username}</span>! You have successfully created a profile.')
            return redirect('users:create-profile')
        
    else:
        form = UserCreationForm()
        
    return render(request, 'users/register.html',{'form':form})

def comments(request):
    return render(request,'users/comments.html')

def profile(request, username):
    # Retrieve the user being viewed
    profile_user = get_object_or_404(User, username=username)

    # Retrieve the profile associated with the user being viewed
    profile = get_object_or_404(Profile, user=profile_user)
    
    # Retrieve the count of blogs associated with the user
    user_blog_count = Blog.objects.filter(author=profile_user).count()    
    
    user_object = User.objects.get(username=username)
    user_profile = Profile.objects.get(user=user_object)
    user_posts = BulletinBoard.objects.filter(user=username)
    user_posts_length = len(user_posts)
    user_followers = FollowersCount.objects.filter(follower=username)
    user_followers_length = len(user_followers)
    user_following = FollowersCount.objects.filter(user=username)
    user_following_length = len(user_following)
    
    follower = request.user.username
    user = username
    
    if FollowersCount.objects.filter(follower=follower, user=user).first():
        button_text = 'Unfollow'  
    else :

users/templates/users/base.html
{% load static %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js"></script>

    <title>
        {% if user.is_authenticated %}
            {{ user.username }}
        {% else %}
            Chikaness
        {% endif %}
    </title>
    <style>
        .fixed-height {
            height: 400px; /* Set the desired fixed height */
        }
        .form-control {
            overflow-y: hidden; /* Hide the vertical scrollbar */
        }
    </style>
</head>
<body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-xxl">
            <a href="{% url 'users:index' %}" class="navbar-brand">
                <span class="fw-bold text-warning">
                    {% if user.is_authenticated %}
                    <i class="bi bi-house-heart"></i>
                    <a href="{% url 'profile' username=user.username %}" class="fw-bold text-warning navbar-brand" style="text-decoration: none; font-size:22px;">{{ user.username }}</a>
                    {% else %}
                    <i class="bi bi-shield-fill-exclamation"></i>
                    Limited access
                    {% endif %}
                </span>
            </a>

            <!-- toggle button -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#main-nav" aria-controls="main-nav" aria-expanded="false"
            aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end align-center" id="main-nav">
                <ul class="navbar-nav">
                    <form class="d-flex" role="search" action="{% url 'users:search' %}" method='POST'>
                        {% csrf_token %}
                        <input class="form-control me-2" name="username" type="text" placeholder="Search for user..." aria-label="Search">
                        <button class="btn btn-outline-warning" type="submit"><i class="bi bi-search-heart"></i></button>
                      </form>
                    <li class="nav-item">
                        <a href="/" class="nav-link text-light"><i class="bi bi-house-door"></i>Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'blogs:blogs' %}" class="nav-link text-light"><i class="bi bi-journal"></i>Blogs</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'logout' %}" class="btn btn-outline-warning">Log Me Out, Gotta Run</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="btn btn-warning">Log Me In</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    
    {% endblock %}
    
    {% comment %} <!-- footer -->
    <footer class="footer mt-auto py-3 bg-dark text-white">
        <div class="container text-center">
            {% if user.is_authenticated %}
            <p>&copy; 2024 {{ user.username }}'s Website. All Rights Reserved.</p>
            {% else %}
            <p>&copy; 2024 Chikaness. All Rights Reserved.</p>
            {% endif %}
        </div>
    </footer> {% endcomment %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- Ensure jQuery is properly loaded -->
    <script>
        function autoAdjustTextarea() {
            const textarea = document.getElementById("floatingTextarea");
            textarea.style.height = "auto";
            textarea.style.height = (textarea.scrollHeight) + "px";
        }

        $( document ).ready(function() {
        let display = false
        // $(".cmt_btn").click(function () {
        //   if (display===false) {
        //     $(this).next(".comment-box").show("slow");
        //     display=true
        //   } else {
        //     $(this).next(".comment-box").hide("slow");
        //   }
        // });

        $('.like-form').submit(function(e) {
            e.preventDefault()
            
            const post_id = $(this).attr('id')
            
            const likeText = $(`.like-btn${post_id}`).text()
            const trim = $.trim(likeText)
            
            const url = $(this).attr('action')
            
            let res;
            const likes = $(`.like-count${post_id}`).text()
            const trimCount = parseInt(likes)
            
            $.ajax({
            type: 'POST',
            url: url,
            data: {
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                'post_id':post_id,
            },
            success: function(response) {
                if(trim === 'Unsend star') {
                $(`.like-btn${post_id}`).text('Send a star')
                res = trimCount - 1
                } else {
                $(`.like-btn${post_id}`).text('Unsend star')
                res = trimCount + 1
                }

                $(`.like-count${post_id}`).text(res)
            },
            error: function(response) {
                console.log('error', response)
            }
            })

        });
        });

        document.addEventListener("DOMContentLoaded", function() {
            // Get all toggle links
            var toggleLinks = document.querySelectorAll(".toggle-link");
        
            // Attach click event listener to each toggle link
            toggleLinks.forEach(function(link) {
                link.addEventListener("click", function(event) {
                    event.preventDefault(); // Prevent default link behavior
        
                    // Get the parent post element
                    var post = this.closest(".bulletin-post");
        
                    // Toggle visibility of full text
                   var fullText = post.querySelector(".full-text");
                    fullText.style.display = (fullText.style.display === "none") ? "inline" : "none";
        
                    //  Change toggle link text
                    this.textContent = (fullText.style.display === "none") ? "Show more" : "Show less";
                });
            });
        });

        lightbox.option({
    'resizeDuration': 200,
    'wrapAround': true
});

    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/likers-modal.html
<!-- Modal -->

{% load static %}

<div class="modal fade" id="likersModal" tabindex="-1" aria-labelledby="likersModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Likers</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                
                <ul>
                    <!-- Display content of the queryset for testing -->
                    <li>Content of likers queryset's user username attribute: {{ likers }}</li>
            
                    <!-- Iterate over likers queryset to display usernames -->
                    {% if likers %}
                        <!-- Likers exist, iterate over them -->
                        {% for liker in likers %}
                            <li>{{ liker.username }}</li>
                        {% endfor %}
                    {% else %}
                        <!-- No likers found -->
                        <p>No likes</p>
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>
</div>

users/templates/users/likers.html
{% extends 'users/base.html' %}

{% block content %}

<div class="pt-5">
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} bg-warning">
        {{ message|safe }}
    </div>
    {% endfor %}
    {% endif %}
</div>
<div class="container">
    <h2 class="display-3 pt-2">Comments & Stars</h2>
    <div class="row mx-6 bg-light justify-content-center align-items-center" style="
        border-radius:20px;">          
        <div class="col-lg-7 text-center border border-top-0 border-warning pb-3">
            {% comment %} <p><a href="{% url 'profile' username=post.user %}" style="text-decoration: none; font-size:50px; font-weight:bolder; color:rgb(87, 2, 87);">{{ post.user }}:</a></p>
            <p style="color:gray;">{{post.content}}</p>
            {% endcomment %}
            <a href="{{ post.image.url }}" data-lightbox="image">
                <img src="{{ post.image.url }}" style="object-fit:cover; width:100%; height: 460px;">
            </a>
                <p class="text-muted my-4" style="text-align: left;">
                <div class="bulletin-post" id="post{{ post.id }}">
                    {{ post.content|truncatewords:60 }}
                        {% if post.content|wordcount > 60 %}
                            <!-- Hidden full text -->
                            <span class="full-text" style="display: none;">
                                {{ post.content }}
                            </span>
                            <!-- Toggle link -->
                            <a href="#" class="toggle-link" style="
                            text-decoration:none; 
                            color:blue;">Show more</a>
                        {% endif %}
                </div>
            </p>            
            <a class="btn btn-outline-warning" 
            href="{% url 'users:user-announcements' username=post.user %}"> {{post.user}}'s announcements</a>            
            <a class="btn btn-warning" 
            href="{% url 'users:show-bulletin-board' %}"> Bulletin Board</a>
            <hr>
            {% if user.is_authenticated %}
            <form action="{% url 'users:add-comment' %}" method="POST" id="{{post.id}}">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{ post.id }}"> <!-- Hidden input field for post ID -->
                <div class="form-group">
                    <label for="id_content">Leave a comment:</label>
                    <textarea class="form-control" id="id_content" name="content" rows="3" required></textarea>
                </div><br>
                <button type="submit" class="btn btn-warning">Submit</button>
            </form>
            {% endif %}
        </div>


        <div class="col-lg-5 py-3">
            
            {% if comments %}
            {% for comment in comments %}
            <p>
            <a href="{% url 'profile' username=post.user %}" style="text-decoration: none;">         
                <span class="text-warning"><b>{{ comment.user }}</b></span>
                <span style="font-size:10px; color:gray;">
                    ({{ post.created_at|date:"M-d-Y" }}):
                </span>                             
            </a>  
                {{comment.content|linebreaks}}
            </p>
            {% endfor %}
            {% else %}
            <p>No comments yet.</p>
            {% endif %}
            <hr>       
            {% if likers %}
            {% for liker in likers %}
                <p><a href="{% url 'profile' username=liker.username %}" style="text-decoration: none;"><img width="30" height="30" style="object-fit:cover; border-radius:15px;"
                src="{{liker.profile.profile_pic.url}}"><span class="text-warning ps-2"><strong>{{liker.username}}</strong></span></a></p>
            {% endfor %}
            {% else %}
                <p class="display-6">No <i class="bi bi-star"></i><i class="bi bi-star-half"></i> yet.<p>
                <p>Be the first person to send a star to this announcement.</p>
                <a class="btn btn-outline-warning" href="{% url 'users:user-announcements' username=post.user %}"> Go back to {{post.user}}'s announcements</a>
            {% endif %}     
            
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/profile_form.html
{% extends 'users/base.html' %}

{% block content %}

<div class="container bg-light px-5 py-5">
    <h2 class="pt-5 display-6">{{ user.username }}, create/edit your profile here...</h2>
    <form method="post" enctype="multipart/form-data" class="px-4 py-3">
      {% csrf_token %}
      <div class="mb-3">
        <img width="100" height="100" style="object-fit:cover; border-radius: 50px; margin-bottom:14px;" src="{{user_profile.profile_pic.url}}" /><br>
        <label for="image" class="form-label fw-bold">Change Profile Image</label>
        <input type="file" name="image" id="image" class="form-control shadow-none bg-gray-100">
      </div>
    
      <div class="mb-3">
        <label for="motto" class="form-label fw-bold">Favorite Expression:</label>
        <textarea id="motto" name="motto" class="form-control">{{user_profile.motto}}</textarea>
      </div>
    
      <div class="mb-3">
        <label for="about_yourself" class="form-label fw-bold">About yourself:</label>
        <textarea id="about_yourself" name="about_yourself" class="form-control">{{user_profile.about_yourself}}</textarea>
      </div>
    
      <div class="mb-3">
        <label for="q1" class="form-label fw-bold">My most memorable experience:</label>
        <textarea id="q1" name="q1" class="form-control">{{user_profile.q1}}</textarea>
      </div>
    
      <div class="mb-3">
        <label for="q2" class="form-label fw-bold">What makes me happy:</label>
        <textarea id="q2" name="q2" class="form-control">{{user_profile.q2}}</textarea>
      </div>
    
      <div class="mb-3">
        <label for="q3" class="form-label fw-bold">My favorites:</label>
        <textarea id="q3" name="q3" class="form-control">{{user_profile.q3}}</textarea>
      </div>
    
      <div class="mb-3">
        <label for="q4" class="form-labe fw-bold">Things most people like but I don't:</label>
        <textarea id="q4" name="q4" class="form-control">{{user_profile.q4}}</textarea>
      </div>
    
      <button type="submit" class="btn btn-primary px-5">Submit</button>
      <a href="{% url 'users:index' %}" class="btn btn-outline-primary px-5">Cancel</a>
     </form>
  </div>
  

{% endblock %}